// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc2I6n0k9v3ptV7sYacDdvlQsa3u26mR0',
    appId: '1:1063765571724:web:c1e1e9195a78e6b08d63a9',
    messagingSenderId: '1063765571724',
    projectId: 'jawsandteeth-app',
    authDomain: 'jawsandteeth-app.firebaseapp.com',
    databaseURL: 'https://jawsandteeth-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jawsandteeth-app.appspot.com',
    measurementId: 'G-HWD34EW1R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGc90vMdFPf4bkNXERLRjnu4cy1s12UE',
    appId: '1:1063765571724:android:679e8acbe06f80368d63a9',
    messagingSenderId: '1063765571724',
    projectId: 'jawsandteeth-app',
    databaseURL: 'https://jawsandteeth-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jawsandteeth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvTwcpmJiGk-gy-l5YLwCJdC2BqWB_wY',
    appId: '1:1063765571724:ios:3b32fcf9dd1bc73b8d63a9',
    messagingSenderId: '1063765571724',
    projectId: 'jawsandteeth-app',
    databaseURL: 'https://jawsandteeth-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jawsandteeth-app.appspot.com',
    iosClientId: '1063765571724-ch29fm8dqkl5hga4mgutqj79se2g6mce.apps.googleusercontent.com',
    iosBundleId: 'com.example.newcodeproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvTwcpmJiGk-gy-l5YLwCJdC2BqWB_wY',
    appId: '1:1063765571724:ios:3b32fcf9dd1bc73b8d63a9',
    messagingSenderId: '1063765571724',
    projectId: 'jawsandteeth-app',
    databaseURL: 'https://jawsandteeth-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jawsandteeth-app.appspot.com',
    iosClientId: '1063765571724-ch29fm8dqkl5hga4mgutqj79se2g6mce.apps.googleusercontent.com',
    iosBundleId: 'com.example.newcodeproj',
  );
}
